name: My first workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        
        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: List and Read file
          run: |
            echo "My first GITHUB ActionsSS"
            ls -ltra
            cat README.md
        
        - name: Generate ASCII Artwork
          run: cowsay -f "run for corver, I am a DRAGON... RWARR" >> dragon.txt
    



        
        #- name: list files
        # run: ls

        #- name: Read File
        #  run: cat README.md