name: Generate ASCII Artwork

on: push
jobs:
    ascii_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        
        - name: check repo
          run: ls -ltra
        
        - name: Executing shell script
          run: |
            chmod +x .github\workflows\ascii_script.sh
            .github\workflows\ascii_script.sh
