name: matrix Configraution


on:
    push: 
    workflow_dispatch:

jobs:
    deploy:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, ubuntu-20.04]
          images: [hello-world, alpine]

          #TOTAL OF 6 Jobs are rynning in parallel.

      runs-on: ${{ matrix.os }} 
      steps:

            - name: echo docker info
              run: docker info

            - name: run IMAGES
              run: docker run ${{ matrix.images }}

              






            

